# Golang CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 3757054c4d98a46b4c1b7f6eb144d0ab2169b27b4b2c14fbc8ecd5d678136d9a
    plugins:
      gofmt:
        enabled: true
      golint:
        enabled: true
      govet:
        enabled: true
    docker:
      # specify the version
      - image: circleci/golang:1.11

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/everettcaleb/envconfig
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: go get -v -t -d ./...
      - run: ./cc-test-reporter before-build
      - run: go test -v -coverprofile=c.out ./...
      - run: ./cc-test-reporter after-build